root: true

parser: babel-eslint

plugins: ["react"]

extends: ["airbnb"]

env:
  browser: true
  es6: true
  node: true

globals:
  ApplicationConfiguration: true
  inject: true
  moment: true
  io: true
  ss: true
  log: true # ??

# TODO: Try to add these rules (use '2' instead of '0' or '1')
rules:
  comma-dangle: 0
  consistent-return: 1
  global-require: 0
  guard-for-in: 1
  import/no-dynamic-require: 1
  import/no-extraneous-dependencies: 1
  import/prefer-default-export: 1
  jsx-a11y/interactive-supports-focus: 1
  jsx-a11y/label-has-for: 1
  jsx-a11y/no-static-element-interactions: 1
  max-len: 0
  no-bitwise: 1
  no-mixed-operators: 1
  no-multi-assign: 1
  no-param-reassign: 1
  no-plusplus: 1
  no-restricted-syntax: 1
  no-shadow: 1 # TODO: important rule ! Use '2' as soon as possible !
  no-underscore-dangle: 1
  no-unused-expressions: 0
  no-use-before-define: 0
  one-var: 1
  radix: 1
  react/forbid-prop-types: 1
  react/jsx-filename-extension: 0
  react/jsx-no-bind: 1
  react/no-array-index-key: 1
  react/prop-types: 1  # TODO: important rule ! Use '2' as soon as possible !
  react/require-default-props: 1 # TODO: important rule ! Use '2' as soon as possible !
  strict: 0